# Generated by Django 2.0.7 on 2018-07-12 18:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=300, verbose_name='地址')),
                ('apt', models.CharField(blank=True, default='', max_length=10, verbose_name='Apartment')),
                ('city', models.CharField(default='', max_length=100, verbose_name='City')),
                ('state', models.CharField(default='', max_length=100, verbose_name='State')),
                ('country', models.CharField(default='', max_length=100, verbose_name='Country')),
                ('zipcode', models.CharField(default='', max_length=5, verbose_name='Zip Code')),
                ('memo', models.TextField(default='', verbose_name='Address Meno')),
                ('first_name', models.CharField(default='', max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(default='', max_length=100, verbose_name='Last Name')),
                ('location_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Location Nickname')),
                ('phone', models.CharField(blank=True, default='', max_length=25, validators=[django.core.validators.RegexValidator(message="Invalid phone number format. Enter as 123-456-0987. Optionally enter extensions using 'x' followed by the number.", regex='^\\s*(?:\\+?(\\d{1,3}))?[-. (]*(\\d{3})[-. )]*(\\d{3})[-. ]*(\\d{4})(?: *x(\\d+))?\\s*$')], verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, default='', max_length=100, verbose_name='Email Address')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(blank=True, default='', max_length=25, validators=[django.core.validators.RegexValidator(message="Invalid phone number format. Enter as 123-456-0987. Optionally enter extensions using 'x' followed by the number.", regex='^\\s*(?:\\+?(\\d{1,3}))?[-. (]*(\\d{3})[-. )]*(\\d{3})[-. ]*(\\d{4})(?: *x(\\d+))?\\s*$')], verbose_name='Phone Number')),
                ('reward', models.PositiveIntegerField(default=0)),
                ('default_address', models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='main.Address', verbose_name='Default Mailing Address')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
