# Generated by Django 2.0.7 on 2018-07-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionpoint',
            name='dimension',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='collectionpoint',
            name='food',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collectionpoint',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='collectionpoint',
            name='luxury',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collectionpoint',
            name='regular',
            field=models.BooleanField(default=False),
        ),
    ]
