# Generated by Django 2.0.7 on 2018-09-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionpoint',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Instruction'),
        ),
        migrations.AlterField(
            model_name='collectionpoint',
            name='fri_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Friday End'),
        ),
        migrations.AlterField(
            model_name='collectionpoint',
            name='fri_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Friday Start'),
        ),
        migrations.AlterField(
            model_name='collectionpoint',
            name='mon_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Monday End'),
        ),
        migrations.AlterField(
            model_name='collectionpoint',
            name='mon_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Monday Start'),
        ),
        migrations.AlterField(
            model_name='collectionpoint',
            name='sat_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Saturday End'),
        ),
        migrations.AlterField(
            model_name='collectionpoint',
            name='sat_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Saturday Start'),
        ),
        migrations.AlterField(
            model_name='collectionpoint',
            name='sun_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Sunday End'),
        ),
        migrations.AlterField(
            model_name='collectionpoint',
            name='sun_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Sunday Start'),
        ),
        migrations.AlterField(
            model_name='collectionpoint',
            name='thu_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Thursday End'),
        ),
        migrations.AlterField(
            model_name='collectionpoint',
            name='thu_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Thursday Start'),
        ),
        migrations.AlterField(
            model_name='collectionpoint',
            name='tue_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Tuesday End'),
        ),
        migrations.AlterField(
            model_name='collectionpoint',
            name='tue_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Tuesday Start'),
        ),
        migrations.AlterField(
            model_name='collectionpoint',
            name='wechat_qrcode',
            field=models.ImageField(blank=True, upload_to='collector_wechat', verbose_name='Wechat QRcode'),
        ),
        migrations.AlterField(
            model_name='collectionpoint',
            name='wed_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Wednesday End'),
        ),
        migrations.AlterField(
            model_name='collectionpoint',
            name='wed_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Wednesday Start'),
        ),
    ]
