# Generated by Django 2.0.7 on 2018-08-02 17:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20180729_1326'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('user', 'follow_user_infor', 'first_name', 'last_name', 'phone', 'email', 'address', 'apt', 'city', 'state', 'country', 'zipcode')},
        ),
    ]
