# Generated by Django 2.0.7 on 2018-07-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180718_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='coreceiver',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='coreceiver',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Last Point Name'),
        ),
    ]
