# Generated by Django 2.0.7 on 2018-09-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180902_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='chinese',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='english',
        ),
        migrations.AddField(
            model_name='resource',
            name='chinese_content',
            field=models.TextField(blank=True, default='', verbose_name='Chinese Version Content'),
        ),
        migrations.AddField(
            model_name='resource',
            name='chinese_file',
            field=models.FileField(blank=True, upload_to='resource/chinese', verbose_name='Chinese Version File'),
        ),
        migrations.AddField(
            model_name='resource',
            name='english_content',
            field=models.TextField(blank=True, default='', verbose_name='English Version Content'),
        ),
        migrations.AddField(
            model_name='resource',
            name='english_file',
            field=models.FileField(blank=True, upload_to='resource/english', verbose_name='English Version File'),
        ),
    ]
