# Generated by Django 2.0.7 on 2018-08-31 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180830_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionpoint',
            name='license_type',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='License Type'),
        ),
    ]
