# Generated by Django 2.0.7 on 2018-09-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180902_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='header',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Header'),
        ),
    ]
