# Generated by Django 2.0.7 on 2018-07-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180718_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='address',
            name='follow_user_infor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Last Name'),
        ),
    ]
