# Generated by Django 2.0.7 on 2018-07-19 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180718_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='ship_to_user',
            new_name='ship_to_add',
        ),
        migrations.AddField(
            model_name='service',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.CoReceiver', verbose_name='Receiver'),
        ),
    ]
