# Generated by Django 2.0.7 on 2018-09-02 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_resource_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionpoint',
            name='agreement',
            field=models.BooleanField(default=False, verbose_name='Agreement'),
        ),
    ]
