# Generated by Django 2.0.7 on 2018-07-20 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180718_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_col',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.CollectionPoint', verbose_name='Default Collection Point'),
        ),
    ]
