# Generated by Django 2.0.7 on 2018-09-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180909_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderset',
            name='currency',
            field=models.CharField(blank=True, choices=[('CNY', 'China Yuan'), ('USD', 'US Dollar')], default='', max_length=100, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Item Value'),
        ),
    ]
