# Generated by Django 2.0.7 on 2018-07-21 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_userprofile_default_col'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='address',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Address', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='coreceiver',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
