# Generated by Django 2.0.7 on 2018-09-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180909_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='order_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Order Amount'),
        ),
        migrations.AddField(
            model_name='service',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Amount'),
        ),
    ]
