# Generated by Django 2.0.7 on 2018-07-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180720_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Item Value'),
        ),
    ]
