# Generated by Django 2.0.7 on 2018-09-10 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180909_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='total_amount',
        ),
    ]
