# Generated by Django 2.0.7 on 2018-07-25 01:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20180721_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteWebsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_type', models.CharField(blank=True, choices=[('Clothing', 'Clothing'), ('Bag', 'Bag'), ('Jewelry', 'Jewelry'), ('Sport', 'Sport'), ('Beauty', 'Beauty'), ('Baby', 'Baby'), ('Other', 'Other')], default='', max_length=32, verbose_name='Websit Type')),
                ('web_name', models.CharField(blank=True, default='', max_length=64, verbose_name='Websit Name')),
                ('web_url', models.URLField(blank=True, default='', max_length=128, verbose_name='Websit url')),
                ('rate', models.PositiveIntegerField(default=1, verbose_name='Rate')),
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(default='', max_length=500, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=16, validators=[django.core.validators.RegexValidator(message="Invalid phone number format. Enter as 123-456-0987. Optionally enter extensions using 'x' followed by the number.", regex='^\\s*(?:\\+?(\\d{1,3}))?[-. (]*(\\d{3})[-. )]*(\\d{3})[-. ]*(\\d{4})(?: *x(\\d+))?\\s*$')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='collectionpoint',
            name='address',
            field=models.CharField(default='', max_length=500, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='collectionpoint',
            name='license',
            field=models.CharField(default='', max_length=32, verbose_name='License Number'),
        ),
        migrations.AlterField(
            model_name='collectionpoint',
            name='license_type',
            field=models.CharField(default='', max_length=32, verbose_name='License Type'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='Item Value'),
        ),
        migrations.AlterField(
            model_name='otherpaymethod',
            name='account_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Account Id'),
        ),
        migrations.AlterField(
            model_name='otherpaymethod',
            name='account_name',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Account Name'),
        ),
        migrations.AlterField(
            model_name='otherpaymethod',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=100, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='parentpackage',
            name='carrier',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Carrier'),
        ),
        migrations.AlterField(
            model_name='parentpackage',
            name='tracking_num',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Tracking Number'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='', max_length=32, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(default='', max_length=32, unique=True, verbose_name='Payment Confirmation'),
        ),
        migrations.AlterField(
            model_name='service',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='service',
            name='cust_carrier',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Customer Carrier'),
        ),
        migrations.AlterField(
            model_name='service',
            name='cust_tracking_num',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Customer Tracking Number'),
        ),
        migrations.AlterField(
            model_name='service',
            name='low_volume_request',
            field=models.BooleanField(default=False, verbose_name='Low Volume Request'),
        ),
        migrations.AlterField(
            model_name='service',
            name='package_type',
            field=models.CharField(blank=True, choices=[('Food', 'Food'), ('Regular', 'Regular'), ('Luxury', 'Luxury'), ('Mix', 'Mix')], default='', max_length=16, verbose_name='Package Type'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Address', verbose_name='Default Mailing Address'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=16, validators=[django.core.validators.RegexValidator(message="Invalid phone number format. Enter as 123-456-0987. Optionally enter extensions using 'x' followed by the number.", regex='^\\s*(?:\\+?(\\d{1,3}))?[-. (]*(\\d{3})[-. )]*(\\d{3})[-. ]*(\\d{4})(?: *x(\\d+))?\\s*$')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='address',
            field=models.CharField(default='', max_length=500, verbose_name='地址'),
        ),
    ]
