# Generated by Django 2.0.7 on 2018-09-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_service_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderset',
            name='currency',
            field=models.CharField(blank=True, choices=[('CNY', 'China Yuan'), ('USD', 'US Dollar')], default='USD', max_length=100, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='orderset',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='user',
            name='reward',
            field=models.PositiveIntegerField(default=0, verbose_name='Reward Points'),
        ),
    ]
