# Generated by Django 2.0.7 on 2018-07-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180724_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritewebsite',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Country'),
        ),
    ]
