# Generated by Django 2.0.7 on 2018-07-25 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_favoritewebsite_country'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('follow_user_infor', 'first_name', 'last_name', 'phone', 'email', 'address', 'apt', 'city', 'state', 'country', 'zipcode')},
        ),
    ]
