# Generated by Django 2.0.7 on 2018-09-12 16:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20180910_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(default='', max_length=16, validators=[django.core.validators.RegexValidator(message='Invalid phone number format. Enter as 1-123-456-7890.', regex='^\\s*(?:\\+?(\\d{1,3}))?[-. (]*(\\d{3})[-. )]*(\\d{3})[-. ]*(\\d{4})(?: *x(\\d+))?\\s*$')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='coreceiver',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=16, validators=[django.core.validators.RegexValidator(message='Invalid phone number format. Enter as 1-123-456-7890.', regex='^\\s*(?:\\+?(\\d{1,3}))?[-. (]*(\\d{3})[-. )]*(\\d{3})[-. ]*(\\d{4})(?: *x(\\d+))?\\s*$')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=16, validators=[django.core.validators.RegexValidator(message='Invalid phone number format. Enter as 1-123-456-7890.', regex='^\\s*(?:\\+?(\\d{1,3}))?[-. (]*(\\d{3})[-. )]*(\\d{3})[-. ]*(\\d{4})(?: *x(\\d+))?\\s*$')], verbose_name='Phone Number'),
        ),
    ]
