# Generated by Django 2.0.7 on 2018-07-25 18:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_auto_20180725_1356'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coreceiver',
            unique_together={('user', 'first_name', 'last_name', 'phone')},
        ),
    ]
