# Generated by Django 2.0.7 on 2018-07-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20180725_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionpoint',
            name='id_image',
            field=models.ImageField(default='', upload_to='collector_id'),
        ),
        migrations.AddField(
            model_name='collectionpoint',
            name='license_image',
            field=models.ImageField(blank='True', upload_to='collector_license'),
        ),
    ]
