# Generated by Django 2.0.7 on 2018-09-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20180912_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionpoint',
            name='wechat',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='WeChat ID'),
        ),
    ]
