# Generated by Django 2.0.7 on 2018-09-13 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20180912_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='country_sortname',
            new_name='country_shortname',
        ),
    ]
