# Generated by Django 2.0.7 on 2018-09-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20180913_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='ship_carrier',
            field=models.CharField(blank=True, choices=[('ZT', 'Zhong Tong'), ('YT', 'Yuan Tong'), ('UPS', 'UPS'), ('DHL', 'DHL')], default='', max_length=100, verbose_name='Select a Carrier'),
        ),
    ]
