# Generated by Django 2.0.7 on 2018-09-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20180916_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('EN', 'English'), ('CN', 'Chinese')], default='', max_length=100, verbose_name='Preferred Language'),
        ),
    ]
