# Generated by Django 2.0.7 on 2018-09-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20180916_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionpoint',
            name='beauty',
            field=models.BooleanField(default=False, verbose_name='Beauty'),
        ),
        migrations.AddField(
            model_name='collectionpoint',
            name='show_contact',
            field=models.BooleanField(default=False, verbose_name='Show Contact Information'),
        ),
    ]
