# Generated by Django 2.0.7 on 2018-09-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20180918_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderset',
            name='insurance_high',
        ),
        migrations.RemoveField(
            model_name='orderset',
            name='insurance_low',
        ),
        migrations.RemoveField(
            model_name='orderset',
            name='insurance_medium',
        ),
        migrations.AddField(
            model_name='orderset',
            name='insurance',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'NO insurance'), (3, '$3 instance'), (5, '$5 instance'), (10, '$10 instance')], default=0, verbose_name='Insurance Plan'),
        ),
    ]
