# Generated by Django 2.1.1 on 2018-09-19 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20180918_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderset',
            name='insurance',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'NO insurance'), (3, '$3 insurance'), (5, '$5 insurance'), (10, '$10 insurance')], default=0, verbose_name='Insurance Plan'),
        ),
    ]
