# Generated by Django 2.1.1 on 2018-09-22 00:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20180919_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionpoint',
            name='wechat_qrcode',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='collector_wechat'),
        ),
    ]
