# Generated by Django 2.1.1 on 2018-09-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20180922_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionpoint',
            name='info_source',
            field=models.CharField(blank=True, choices=[('WC', 'WeChat'), ('DM', 'Dealmoon')], default='', max_length=100, verbose_name='Information Source'),
        ),
        migrations.AlterField(
            model_name='parentpackage',
            name='carrier',
            field=models.CharField(blank=True, choices=[('SF', 'ShunFeng／顺丰速运'), ('ChinaPost', 'YouZheng／中国邮政'), ('ZTO', 'ZhongTong／中通速递'), ('YTO', 'YuanTong／圆通速递'), ('STO', 'ShenTong／申通速递'), ('ZJS', 'ZhaiJiSong／宅急送'), ('YD', 'YunDa／韵达快递'), ('JD', 'JingDong／京东物流'), ('BS', 'BaiShi／百世快递'), ('TTK', 'Tiantian／天天快递'), ('EYB', 'EyouBao／E邮宝'), ('AAE', 'AAE／AAE快递'), ('ADA', 'AnDa／安达速递'), ('DP', 'DeBang／德邦快递'), ('DD', 'DangDang／当当网'), ('UCE', 'YouSu／优速快递'), ('QF', 'QuanFeng／全峰快递'), ('QY', 'QuanYi／全一快递'), ('DHL', 'DHL'), ('EMS', 'EMS'), ('FEDEX', 'FedEx／联邦快递'), ('SF EXPRESS', 'SF EXPRESS／顺丰速运'), ('UPS', 'UPS/联合国际快递'), ('OTHERS', 'Others／其他')], default='', max_length=100, verbose_name='Carrier'),
        ),
        migrations.AlterField(
            model_name='service',
            name='cust_carrier',
            field=models.CharField(blank=True, choices=[('SF', 'ShunFeng／顺丰速运'), ('ChinaPost', 'YouZheng／中国邮政'), ('ZTO', 'ZhongTong／中通速递'), ('YTO', 'YuanTong／圆通速递'), ('STO', 'ShenTong／申通速递'), ('ZJS', 'ZhaiJiSong／宅急送'), ('YD', 'YunDa／韵达快递'), ('JD', 'JingDong／京东物流'), ('BS', 'BaiShi／百世快递'), ('TTK', 'Tiantian／天天快递'), ('EYB', 'EyouBao／E邮宝'), ('AAE', 'AAE／AAE快递'), ('ADA', 'AnDa／安达速递'), ('DP', 'DeBang／德邦快递'), ('DD', 'DangDang／当当网'), ('UCE', 'YouSu／优速快递'), ('QF', 'QuanFeng／全峰快递'), ('QY', 'QuanYi／全一快递'), ('DHL', 'DHL'), ('EMS', 'EMS'), ('FEDEX', 'FedEx／联邦快递'), ('SF EXPRESS', 'SF EXPRESS／顺丰速运'), ('UPS', 'UPS/联合国际快递'), ('OTHERS', 'Others／其他')], default='', max_length=100, verbose_name="Customer's Package's Carrier"),
        ),
        migrations.AlterField(
            model_name='service',
            name='last_carrier',
            field=models.CharField(blank=True, choices=[('SF', 'ShunFeng／顺丰速运'), ('ChinaPost', 'YouZheng／中国邮政'), ('ZTO', 'ZhongTong／中通速递'), ('YTO', 'YuanTong／圆通速递'), ('STO', 'ShenTong／申通速递'), ('ZJS', 'ZhaiJiSong／宅急送'), ('YD', 'YunDa／韵达快递'), ('JD', 'JingDong／京东物流'), ('BS', 'BaiShi／百世快递'), ('TTK', 'Tiantian／天天快递'), ('EYB', 'EyouBao／E邮宝'), ('AAE', 'AAE／AAE快递'), ('ADA', 'AnDa／安达速递'), ('DP', 'DeBang／德邦快递'), ('DD', 'DangDang／当当网'), ('UCE', 'YouSu／优速快递'), ('QF', 'QuanFeng／全峰快递'), ('QY', 'QuanYi／全一快递'), ('DHL', 'DHL'), ('EMS', 'EMS'), ('FEDEX', 'FedEx／联邦快递'), ('SF EXPRESS', 'SF EXPRESS／顺丰速运'), ('UPS', 'UPS/联合国际快递'), ('OTHERS', 'Others／其他')], default='', max_length=100, verbose_name='Final Shipping Carrier'),
        ),
        migrations.AlterField(
            model_name='service',
            name='package_type',
            field=models.CharField(blank=True, choices=[('F', 'Food'), ('R', 'Regular'), ('B', 'Beauty'), ('L', 'Luxury'), ('M', 'Mix')], default='', max_length=16, verbose_name='Package Type'),
        ),
        migrations.AlterField(
            model_name='service',
            name='ship_carrier',
            field=models.CharField(blank=True, choices=[('DHL', 'DHL'), ('EMS', 'EMS'), ('FEDEX', 'FEDEX'), ('SF EXPRESS', 'SF EXPRESS'), ('UPS', 'UPS'), ('Cheapest', 'The cheapest one'), ('Fastest', 'The fastest one')], default='', max_length=100, verbose_name='Select a Carrier'),
        ),
    ]
