# Generated by Django 2.1.1 on 2018-09-29 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20180929_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='privacy_policy_agree',
            field=models.BooleanField(default=False, verbose_name='Privacy Policy Agreement'),
        ),
    ]
