# Generated by Django 2.1.1 on 2018-10-01 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20180930_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='header',
        ),
        migrations.AddField(
            model_name='resource',
            name='chinese_header',
            field=models.CharField(default='', max_length=100, verbose_name='Chinese Header'),
        ),
        migrations.AddField(
            model_name='resource',
            name='english_header',
            field=models.CharField(default='', max_length=100, verbose_name='English Header'),
        ),
    ]
