# Generated by Django 2.1.1 on 2018-10-01 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20181001_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('ship', 'Shipping Price'), ('currency', 'Currency Rate')], default='', max_length=50, verbose_name='Category')),
                ('form', models.CharField(blank=True, choices=[('cn', 'China'), ('us', 'United States')], default='', max_length=50, verbose_name='City')),
                ('to', models.CharField(blank=True, choices=[('cn', 'China'), ('us', 'United States')], default='', max_length=50, verbose_name='City')),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price/Rate')),
            ],
        ),
    ]
