# Generated by Django 2.1.1 on 2018-10-01 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_pricerate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricerate',
            name='paid_amount',
        ),
        migrations.AddField(
            model_name='pricerate',
            name='avg_weight_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Average Weight Price'),
        ),
        migrations.AddField(
            model_name='pricerate',
            name='carrier',
            field=models.CharField(blank=True, choices=[('SF', 'ShunFeng／顺丰速运'), ('ChinaPost', 'YouZheng／中国邮政'), ('ZTO', 'ZhongTong／中通速递'), ('YTO', 'YuanTong／圆通速递'), ('STO', 'ShenTong／申通速递'), ('ZJS', 'ZhaiJiSong／宅急送'), ('YD', 'YunDa／韵达快递'), ('JD', 'JingDong／京东物流'), ('BS', 'BaiShi／百世快递'), ('TTK', 'Tiantian／天天快递'), ('EYB', 'EyouBao／E邮宝'), ('AAE', 'AAE／AAE快递'), ('ADA', 'AnDa／安达速递'), ('DP', 'DeBang／德邦快递'), ('DD', 'DangDang／当当网'), ('UCE', 'YouSu／优速快递'), ('QF', 'QuanFeng／全峰快递'), ('QY', 'QuanYi／全一快递'), ('DHL', 'DHL'), ('EMS', 'EMS'), ('FEDEX', 'FedEx／联邦快递'), ('SF EXPRESS', 'SF EXPRESS／顺丰速运'), ('UPS', 'UPS/联合国际快递'), ('OTHERS', 'Others／其他')], default='', max_length=100, verbose_name='Shipping Carrier'),
        ),
        migrations.AddField(
            model_name='pricerate',
            name='first_weight_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='First Weight Price'),
        ),
        migrations.AddField(
            model_name='pricerate',
            name='next_weight_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='First Weight Price'),
        ),
        migrations.AddField(
            model_name='pricerate',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Currency Rate'),
        ),
        migrations.AddField(
            model_name='pricerate',
            name='shipping_currency',
            field=models.CharField(blank=True, choices=[('CNY', 'China Yuan'), ('USD', 'US Dollar')], default='USD', max_length=100, verbose_name='Currency for Shipping Price'),
        ),
    ]
