# Generated by Django 2.1.1 on 2018-10-01 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20181001_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricerate',
            name='form',
        ),
        migrations.RemoveField(
            model_name='pricerate',
            name='to',
        ),
        migrations.AddField(
            model_name='pricerate',
            name='from_country',
            field=models.CharField(blank=True, choices=[('cn', 'China'), ('us', 'United States')], default='', max_length=50, verbose_name='From Country'),
        ),
        migrations.AddField(
            model_name='pricerate',
            name='to_country',
            field=models.CharField(blank=True, choices=[('cn', 'China'), ('us', 'United States')], default='', max_length=50, verbose_name='To_Country'),
        ),
    ]
