# Generated by Django 2.1.1 on 2018-10-01 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20181001_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricerate',
            name='package_type',
            field=models.CharField(blank=True, choices=[('F', 'Food'), ('R', 'Regular'), ('B', 'Beauty'), ('L', 'Luxury'), ('M', 'Mix')], default='', max_length=16, verbose_name='Package Type'),
        ),
    ]
