# Generated by Django 2.1.1 on 2018-10-01 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20181001_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricerate',
            name='next_weight_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Next Weight Price'),
        ),
    ]
