# Generated by Django 2.1.1 on 2018-11-04 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_collectionpoint_paypal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cust_carrier',
            field=models.CharField(blank=True, choices=[('SF', 'ShunFeng／顺丰速运'), ('ChinaPost', 'YouZheng／中国邮政'), ('ZTO', 'ZhongTong／中通速递'), ('YTO', 'YuanTong／圆通速递'), ('STO', 'ShenTong／申通速递'), ('ZJS', 'ZhaiJiSong／宅急送'), ('YD', 'YunDa／韵达快递'), ('JD', 'JingDong／京东物流'), ('BS', 'BaiShi／百世快递'), ('TTK', 'Tiantian／天天快递'), ('EYB', 'EyouBao／E邮宝'), ('AAE', 'AAE／AAE快递'), ('ADA', 'AnDa／安达速递'), ('DP', 'DeBang／德邦快递'), ('DD', 'DangDang／当当网'), ('UCE', 'YouSu／优速快递'), ('QF', 'QuanFeng／全峰快递'), ('QY', 'QuanYi／全一快递'), ('DHL', 'DHL'), ('EMS', 'EMS'), ('FEDEX', 'FedEx／联邦快递'), ('SF EXPRESS', 'SF EXPRESS／顺丰速运'), ('UPS', 'UPS/联合国际快递'), ('OTHERS', 'Others／其他')], default='', max_length=100, verbose_name='Original Package Carrier'),
        ),
        migrations.AlterField(
            model_name='service',
            name='cust_tracking_num',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name="Original's Package's Tracking Number"),
        ),
        migrations.AlterField(
            model_name='service',
            name='low_volume_request',
            field=models.BooleanField(default=True, verbose_name='Low Volume Request'),
        ),
        migrations.AlterField(
            model_name='service',
            name='wh_received',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='received_at_warehouse', to='main.Warehouse', verbose_name='Inter-warehouse'),
        ),
    ]
