# Generated by Django 2.1.1 on 2018-11-04 04:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_auto_20181104_0005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagesnapshot',
            options={'ordering': ['package'], 'verbose_name_plural': 'Package Snapshots'},
        ),
        migrations.AlterField(
            model_name='collectionpoint',
            name='collector_icon',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Collector Icon'),
        ),
        migrations.AlterField(
            model_name='collectionpoint',
            name='id_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Collector ID'),
        ),
        migrations.AlterField(
            model_name='collectionpoint',
            name='license_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Collector License'),
        ),
        migrations.AlterField(
            model_name='collectionpoint',
            name='wechat_qrcode',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Collector WeChat'),
        ),
        migrations.AlterField(
            model_name='packagesnapshot',
            name='snapshot',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Package Snapshot'),
        ),
    ]
