# Generated by Django 2.1.1 on 2018-11-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_auto_20181104_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionpoint',
            name='absent_start',
            field=models.DateField(blank=True, null=True, verbose_name='Absent'),
        ),
        migrations.AlterField(
            model_name='collectionpoint',
            name='fri_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Friday'),
        ),
        migrations.AlterField(
            model_name='collectionpoint',
            name='mon_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Monday'),
        ),
        migrations.AlterField(
            model_name='collectionpoint',
            name='sat_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Saturday'),
        ),
        migrations.AlterField(
            model_name='collectionpoint',
            name='sun_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Sunday'),
        ),
        migrations.AlterField(
            model_name='collectionpoint',
            name='thu_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Thursday'),
        ),
        migrations.AlterField(
            model_name='collectionpoint',
            name='tue_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Tuesday'),
        ),
        migrations.AlterField(
            model_name='collectionpoint',
            name='wed_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Wednesday'),
        ),
    ]
