# Generated by Django 2.1.1 on 2018-11-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_auto_20181104_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cust_tracking_num',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name="Original Package's Tracking Number"),
        ),
    ]
