# Generated by Django 2.1.1 on 2018-11-13 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_auto_20181104_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentpackage',
            name='order_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.OrderSet', verbose_name='Order Set'),
        ),
        migrations.AddField(
            model_name='parentpackage',
            name='package_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Direct Shipping Package Amount'),
        ),
    ]
