# Generated by Django 2.1.1 on 2018-11-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_auto_20181113_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentpackage',
            name='currency',
            field=models.CharField(blank=True, choices=[('CNY', 'China Yuan'), ('USD', 'US Dollar')], default='', max_length=100, verbose_name='Currency'),
        ),
    ]
