# Generated by Django 2.1.1 on 2018-11-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_parentpackage_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentpackage',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Paid Amount'),
        ),
    ]
