# Generated by Django 2.1.1 on 2018-11-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_parentpackage_paid_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderset',
            name='reward_point_used',
        ),
        migrations.AlterField(
            model_name='orderset',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Total Amount'),
        ),
    ]
