# Generated by Django 2.1.1 on 2018-11-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_auto_20181116_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderset',
            name='insurance',
            field=models.PositiveIntegerField(choices=[(0, 'NO insurance'), (3, '$3 insurance'), (5, '$5 insurance'), (10, '$10 insurance'), (15, '$15 insurance')], default=0, verbose_name='Insurance Plan'),
        ),
    ]
