# Generated by Django 2.1.1 on 2018-12-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_auto_20181116_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentpackage',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Weight(kg)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='volume_weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Volume Weight(kg)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Weight(kg)'),
        ),
        migrations.AlterUniqueTogether(
            name='pricerate',
            unique_together={('category', 'from_country', 'to_country', 'package_type', 'carrier')},
        ),
    ]
