# Generated by Django 2.1.1 on 2018-12-19 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_auto_20181218_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionpoint',
            name='skincare',
        ),
    ]
