# Generated by Django 2.1.1 on 2018-12-20 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_auto_20181220_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionpoint',
            name='collector',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Collector'),
        ),
    ]
