# Generated by Django 2.1.1 on 2018-12-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_parentpackage_package_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentpackage',
            name='carrier',
            field=models.CharField(blank=True, choices=[('DHL', 'DHL'), ('EMS', 'EMS'), ('FEDEX', 'FEDEX'), ('SF EXPRESS', 'SF EXPRESS'), ('UPS', 'UPS'), ('DHL+', 'DHL 21kg+'), ('EMS+', 'EMS 21kg+'), ('FEDEX+', 'FEDEX 21kg+'), ('SF EXPRESS+', 'SF EXPRESS 21kg+'), ('UPS+', 'UPS 21kg+')], default='', max_length=100, verbose_name='Carrier'),
        ),
    ]
