# Generated by Django 2.1.1 on 2019-01-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_auto_20181222_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderset',
            name='payment_confirmed',
            field=models.BooleanField(default=False, verbose_name='Payment Confirmed'),
        ),
        migrations.AddField(
            model_name='orderset',
            name='tx',
            field=models.CharField(blank=True, max_length=30, verbose_name='tx From PayPal'),
        ),
    ]
