# Generated by Django 2.1.1 on 2018-12-20 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='creater',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='receiver',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.CollectionPoint'),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='creater',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='responseto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='collector.Question'),
        ),
        migrations.AlterField(
            model_name='review',
            name='creater',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='receiver',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.CollectionPoint'),
        ),
        migrations.AlterField(
            model_name='reviewresponse',
            name='creater',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reviewresponse',
            name='responseto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='collector.Review'),
        ),
    ]
