# Generated by Django 2.0.7 on 2018-08-21 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_auto_20180818_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='creater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='question',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.CollectionPoint'),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='creater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='meaasage',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='responseto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collector.Question'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='creater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.CollectionPoint'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='reviewresponse',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reviewresponse',
            name='creater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reviewresponse',
            name='meaasage',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='reviewresponse',
            name='responseto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collector.Review'),
        ),
    ]
